### ISSUE TITLE
Xbox controller imput detection not working on Manjaro Linux

### ISSUE THREAD

**Issue by MimzyFang** [LambdAurora/LambdaControls#38]
**Describe the bug**
I cant use an Xbox controller on Manjaro Linux
it detects it but cant use it
(not tested with other controllers)

**To Reproduce**
1. Install Manjaro Linux
2. install the xow driver for dongle support (optional) https://github.com/medusalix/xow
3. Install Minecraft and all things to run the mod
4. Start Minecraft and try to use the controller 

**Expected behavior**
It should detect controller inputs

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (KDE) https://manjaro.org/download/
 - Minecraft 1.16.4
 - Fabric 0.10.8
 - Mods fabricapi lambdacontrols-fabric
 - Version 1.5.0
 - Branch Release

**Comment by ImperatorStorm** [comment]
Manjaro tends to be a somewhat broken OS

keep that in mind

**Comment by MimzyFang** [comment]
it works perfect with other controller mods like Controllable

**Comment by LambdAurora** [comment]
1. Have you set controller input to Controller
2. When selecting the controller, does it show orange?
   - if it shows orange, have you made mappings for the controller and set them via the mappings editor string in LambdaControls?

**Comment by MimzyFang** [comment]
1. yes i did
2. and it is white
![Screenshot_20201205_201805](https://user-images.githubusercontent.com/43648117/101261374-0d409f80-3737-11eb-877f-d4ada6036b99.png)

**Comment by LambdAurora** [comment]
As long as the controller name is white like this, the only explanation I have is you try to use a wireless controller? And wireless controllers are currently broken on any Linux system because of GLFW, if you want it to work you might need to update the version of GLFW Minecraft use.

![image](https://user-images.githubusercontent.com/12587332/101261417-51cc3b00-3737-11eb-88be-7cd4647ee052.png)

**Comment by MimzyFang** [comment]
ok i looked in the wronk place thank you

**Comment by MimzyFang** [comment]
it is orange

**Comment by iTzSRTW** [comment]
> it is orange

Hey @LambdAurora, do you mind if I take this issue? It's gone unanswered and may be useful for future readers 🙂

@Fauli1221 I know it's been a couple of months since your last reply, if you're still having the same issue(s) can you try the following?

1. Download, install, and run [SDL2 Gamepad Tool](https://generalarcade.com/gamepadtool/) as advised
2. Test all buttons on the controller, the UI should appear green per the button pressed
3. If buttons do not appear correct, click **Create A New Mapping**
  a. Run through the guided configuration
  b. Continue to step 4
4. If all buttons are correctly mapped (i.e; all light up green) click **Copy Mapping String**
  a. Create a new file `~/.minecraft/config/gamecontrollerdb.txt` and paste in the content you just copied
  b. Launch Minecraft

_I am assuming the default Minecraft installation location and configuration, make changes where needed_

**Comment by LambdAurora** [comment]
@srtw With latest versions of LambdaControls step 4 changed a bit, there's directly a file editor in LambdaControls to avoid confusion with the file.

**Comment by iTzSRTW** [comment]
> @srtw With latest versions of LambdaControls step 4 changed a bit, there's directly a file editor in LambdaControls to avoid confusion with the file.

Ah, I was not aware of such editor. With v1.5.0 the in-game configuration still advises the use of the software and steps above, my mistake!

**Comment by MimzyFang** [comment]
I figured it out myself that's why I closed the issue.

I probably should have made that more clear back then
