### ISSUE TITLE
More information regarding joycon compatibility

### ISSUE THREAD

**Issue by whjochim** [LambdAurora/LambdaControls#45]
I'm currently trying to run Java Minecraft 1.16.5 on the Nintendo Switch, and succeeded.  
Now it would be nice to get the JoyCons working.
I added a gamecontrollerdb.txt which includes joycond profiles. The Game recognizes the Combined Controller (show's it in the selection menu), but the inputs aren't registered. An Xbox One Wired Controller can be used on the Switch without problems.

An attempt to use the JoyCons via Bluetooth and joycond on an ordinary Linux Laptop was also unsuccessful.

Could you elaborate which setup you've got working, so I could try to replicate it, and maybe get a step closer to running Minecraft on the Switch? Any help would be appreciated

**Comment by LambdAurora** [comment]
I personally don't have joycons, but some people on my server made it work (and that's why it's marked as compatible), on Windows some used [a third-party software](https://github.com/Davidobot/BetterJoy).

I would suggest you to join [my Discord server](https://discord.gg/abEbzzv), the issue already has been analyzed on the server and the solution was a patch to joycond, more here: https://discord.com/channels/734886100388151378/736562540099797063/764978394181533716

Hopefully that can help you!

**Comment by whjochim** [comment]
Nevermind, my configuration in gamecontrollerdb.txt was wrong, and the file from user gman on your Discord did the trick! Thank you! All works now
