### ISSUE TITLE
Let optifine and optifabric

### ISSUE THREAD

**Issue by gamemaster64665** [LambdAurora/LambdaControls#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LambdAurora** [comment]
I'm not willing to spend time to deal with mods not caring about the modding ecosystem and breaking fundamental mechanics.

**Comment by gamemaster64665** [comment]
Let optifine and optifabric work on this mod why

**Comment by asiekierka** [comment]
Here's an alternative idea: No.

OptiFine's licensing terms and closed-source nature make adding compatibility to it by other mods quite burdensome. Modders are generally volunteers, and many are not willing to put in extra steps for something they are not personally interested in. What you can do is ask sp614x to add the necessary functionality to OptiFine instead, or to make the mod open source so that modders can add compatibility with it on their own terms.

Or, I guess, pay LambdAurora for her time.
